apiVersion: v1
kind: Service
metadata:
  name: telco-anomaly-webhook
  namespace: telco-healthcheck-system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: telco-anomaly-webhook-cert
spec:
  selector:
    app: telco-anomaly-controller
  ports:
    - name: webhook
      port: 443
      targetPort: 9443
      protocol: TCP
