//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSpec) DeepCopyInto(out *AlertsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSpec.
func (in *AlertsSpec) DeepCopy() *AlertsSpec {
	if in == nil {
		return nil
	}
	out := new(AlertsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedClustersSpec) DeepCopyInto(out *ManagedClustersSpec) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedClustersSpec.
func (in *ManagedClustersSpec) DeepCopy() *ManagedClustersSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedClustersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeriodicHealthChecksSpec) DeepCopyInto(out *PeriodicHealthChecksSpec) {
	*out = *in
	out.Period = in.Period
	in.RDSCompliance.DeepCopyInto(&out.RDSCompliance)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeriodicHealthChecksSpec.
func (in *PeriodicHealthChecksSpec) DeepCopy() *PeriodicHealthChecksSpec {
	if in == nil {
		return nil
	}
	out := new(PeriodicHealthChecksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDSComplianceSpec) DeepCopyInto(out *RDSComplianceSpec) {
	*out = *in
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDSComplianceSpec.
func (in *RDSComplianceSpec) DeepCopy() *RDSComplianceSpec {
	if in == nil {
		return nil
	}
	out := new(RDSComplianceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthcheck) DeepCopyInto(out *TelcoHealthcheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthcheck.
func (in *TelcoHealthcheck) DeepCopy() *TelcoHealthcheck {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthcheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelcoHealthcheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthcheckList) DeepCopyInto(out *TelcoHealthcheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TelcoHealthcheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthcheckList.
func (in *TelcoHealthcheckList) DeepCopy() *TelcoHealthcheckList {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthcheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelcoHealthcheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthcheckSpec) DeepCopyInto(out *TelcoHealthcheckSpec) {
	*out = *in
	in.ManagedClusters.DeepCopyInto(&out.ManagedClusters)
	if in.ManagedNamespaces != nil {
		in, out := &in.ManagedNamespaces, &out.ManagedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Alerts = in.Alerts
	in.PeriodicHealthChecks.DeepCopyInto(&out.PeriodicHealthChecks)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthcheckSpec.
func (in *TelcoHealthcheckSpec) DeepCopy() *TelcoHealthcheckSpec {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthcheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthcheckStatus) DeepCopyInto(out *TelcoHealthcheckStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MonitoredClusters != nil {
		in, out := &in.MonitoredClusters, &out.MonitoredClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastPeriodicRunTime != nil {
		in, out := &in.LastPeriodicRunTime, &out.LastPeriodicRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastRDSComplianceRunTime != nil {
		in, out := &in.LastRDSComplianceRunTime, &out.LastRDSComplianceRunTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthcheckStatus.
func (in *TelcoHealthcheckStatus) DeepCopy() *TelcoHealthcheckStatus {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthcheckStatus)
	in.DeepCopyInto(out)
	return out
}
