//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticRunStatus) DeepCopyInto(out *AgenticRunStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticRunStatus.
func (in *AgenticRunStatus) DeepCopy() *AgenticRunStatus {
	if in == nil {
		return nil
	}
	out := new(AgenticRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertManagerCredentialsSecret) DeepCopyInto(out *AlertManagerCredentialsSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertManagerCredentialsSecret.
func (in *AlertManagerCredentialsSecret) DeepCopy() *AlertManagerCredentialsSecret {
	if in == nil {
		return nil
	}
	out := new(AlertManagerCredentialsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertManagerSpec) DeepCopyInto(out *AlertManagerSpec) {
	*out = *in
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(AlertManagerCredentialsSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertManagerSpec.
func (in *AlertManagerSpec) DeepCopy() *AlertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(AlertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertNotification) DeepCopyInto(out *AlertNotification) {
	*out = *in
	in.StartsAt.DeepCopyInto(&out.StartsAt)
	if in.EndsAt != nil {
		in, out := &in.EndsAt, &out.EndsAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertNotification.
func (in *AlertNotification) DeepCopy() *AlertNotification {
	if in == nil {
		return nil
	}
	out := new(AlertNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSpec) DeepCopyInto(out *AlertsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSpec.
func (in *AlertsSpec) DeepCopy() *AlertsSpec {
	if in == nil {
		return nil
	}
	out := new(AlertsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LowLatencyCheckSpec) DeepCopyInto(out *LowLatencyCheckSpec) {
	*out = *in
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MinJitter != nil {
		in, out := &in.MinJitter, &out.MinJitter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxJitter != nil {
		in, out := &in.MaxJitter, &out.MaxJitter
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LowLatencyCheckSpec.
func (in *LowLatencyCheckSpec) DeepCopy() *LowLatencyCheckSpec {
	if in == nil {
		return nil
	}
	out := new(LowLatencyCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedClustersSpec) DeepCopyInto(out *ManagedClustersSpec) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedClustersSpec.
func (in *ManagedClustersSpec) DeepCopy() *ManagedClustersSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedClustersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeriodicHealthChecksSpec) DeepCopyInto(out *PeriodicHealthChecksSpec) {
	*out = *in
	out.Period = in.Period
	if in.MinJitter != nil {
		in, out := &in.MinJitter, &out.MinJitter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxJitter != nil {
		in, out := &in.MaxJitter, &out.MaxJitter
		*out = new(v1.Duration)
		**out = **in
	}
	in.RDSCompliance.DeepCopyInto(&out.RDSCompliance)
	in.LowLatencyCheck.DeepCopyInto(&out.LowLatencyCheck)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeriodicHealthChecksSpec.
func (in *PeriodicHealthChecksSpec) DeepCopy() *PeriodicHealthChecksSpec {
	if in == nil {
		return nil
	}
	out := new(PeriodicHealthChecksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDSComplianceSpec) DeepCopyInto(out *RDSComplianceSpec) {
	*out = *in
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MinJitter != nil {
		in, out := &in.MinJitter, &out.MinJitter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxJitter != nil {
		in, out := &in.MaxJitter, &out.MaxJitter
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDSComplianceSpec.
func (in *RDSComplianceSpec) DeepCopy() *RDSComplianceSpec {
	if in == nil {
		return nil
	}
	out := new(RDSComplianceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthCheckRun) DeepCopyInto(out *TelcoHealthCheckRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthCheckRun.
func (in *TelcoHealthCheckRun) DeepCopy() *TelcoHealthCheckRun {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthCheckRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelcoHealthCheckRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthCheckRunList) DeepCopyInto(out *TelcoHealthCheckRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TelcoHealthCheckRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthCheckRunList.
func (in *TelcoHealthCheckRunList) DeepCopy() *TelcoHealthCheckRunList {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthCheckRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelcoHealthCheckRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthCheckRunSpec) DeepCopyInto(out *TelcoHealthCheckRunSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthCheckRunSpec.
func (in *TelcoHealthCheckRunSpec) DeepCopy() *TelcoHealthCheckRunSpec {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthCheckRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthCheckRunStatus) DeepCopyInto(out *TelcoHealthCheckRunStatus) {
	*out = *in
	if in.AgenticRunStatus != nil {
		in, out := &in.AgenticRunStatus, &out.AgenticRunStatus
		*out = new(AgenticRunStatus)
		**out = **in
	}
	if in.AlertNotifications != nil {
		in, out := &in.AlertNotifications, &out.AlertNotifications
		*out = make([]AlertNotification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertStartsAt != nil {
		in, out := &in.AlertStartsAt, &out.AlertStartsAt
		*out = (*in).DeepCopy()
	}
	if in.LastAlertSentTime != nil {
		in, out := &in.LastAlertSentTime, &out.LastAlertSentTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthCheckRunStatus.
func (in *TelcoHealthCheckRunStatus) DeepCopy() *TelcoHealthCheckRunStatus {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthCheckRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthcheck) DeepCopyInto(out *TelcoHealthcheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthcheck.
func (in *TelcoHealthcheck) DeepCopy() *TelcoHealthcheck {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthcheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelcoHealthcheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthcheckList) DeepCopyInto(out *TelcoHealthcheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TelcoHealthcheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthcheckList.
func (in *TelcoHealthcheckList) DeepCopy() *TelcoHealthcheckList {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthcheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelcoHealthcheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthcheckSpec) DeepCopyInto(out *TelcoHealthcheckSpec) {
	*out = *in
	if in.AlertManager != nil {
		in, out := &in.AlertManager, &out.AlertManager
		*out = new(AlertManagerSpec)
		(*in).DeepCopyInto(*out)
	}
	in.ManagedClusters.DeepCopyInto(&out.ManagedClusters)
	if in.ManagedNamespaces != nil {
		in, out := &in.ManagedNamespaces, &out.ManagedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Alerts = in.Alerts
	in.PeriodicHealthChecks.DeepCopyInto(&out.PeriodicHealthChecks)
	if in.PurgeInterval != nil {
		in, out := &in.PurgeInterval, &out.PurgeInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthcheckSpec.
func (in *TelcoHealthcheckSpec) DeepCopy() *TelcoHealthcheckSpec {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthcheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelcoHealthcheckStatus) DeepCopyInto(out *TelcoHealthcheckStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MonitoredClusters != nil {
		in, out := &in.MonitoredClusters, &out.MonitoredClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastPeriodicRunTime != nil {
		in, out := &in.LastPeriodicRunTime, &out.LastPeriodicRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastRDSComplianceRunTime != nil {
		in, out := &in.LastRDSComplianceRunTime, &out.LastRDSComplianceRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastLowLatencyCheckRunTime != nil {
		in, out := &in.LastLowLatencyCheckRunTime, &out.LastLowLatencyCheckRunTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelcoHealthcheckStatus.
func (in *TelcoHealthcheckStatus) DeepCopy() *TelcoHealthcheckStatus {
	if in == nil {
		return nil
	}
	out := new(TelcoHealthcheckStatus)
	in.DeepCopyInto(out)
	return out
}
